src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java
Arrumei o template de pull request que não estava funcionando
=> Testando pull

src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java, src/main/resources/application.properties
adicionando env file
novo arquivo .env
=> Application propperties

src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioController.java, src/main/java/com/example/hestiaapipostgres/dto/UpdateUniversityDTO.java, src/main/java/com/example/hestiaapipostgres/exceptions/CustomErrorResponse.java, src/main/java/com/example/hestiaapipostgres/exceptions/GlobalExceptionHandler.java, src/main/java/com/example/hestiaapipostgres/models/Universitario.java, src/main/java/com/example/hestiaapipostgres/repository/AnuncianteRepository.java, src/main/java/com/example/hestiaapipostgres/repository/UniversitarioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java
adicionando endpoint de update do universitário
novo tratamento de erro
novo DTO
=> adicionando rota de update de universitário

src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java, src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioController.java, src/main/java/com/example/hestiaapipostgres/dto/RegisterAdDTO.java, src/main/java/com/example/hestiaapipostgres/dto/UpdateAdvertiserDTO.java, src/main/java/com/example/hestiaapipostgres/dto/perfil/AnuncianteProfileInfo.java, src/main/java/com/example/hestiaapipostgres/dto/perfil/UniversitarioProfileInfo.java, src/main/java/com/example/hestiaapipostgres/models/Anuncio.java, src/main/java/com/example/hestiaapipostgres/models/Plano.java, src/main/java/com/example/hestiaapipostgres/models/Universitario.java, src/main/java/com/example/hestiaapipostgres/repository/AnuncioRepository.java, src/main/java/com/example/hestiaapipostgres/repository/UniversitarioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/AnuncioService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java
adicionando DTO base para registro de anúncio
novo DTO, novos campos na entidade, uma alteração na rota de universitário
=> base da estrutura de anuncio

src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java, src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioController.java, src/main/java/com/example/hestiaapipostgres/controllers/UsuarioController.java, src/main/java/com/example/hestiaapipostgres/dto/InfoUserDTO.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterAdDTO.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterAdvertiserDTO.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterUniversityDTO.java, src/main/java/com/example/hestiaapipostgres/dto/update/UpdateAdvertiserDTO.java, src/main/java/com/example/hestiaapipostgres/dto/update/UpdateUniversityDTO.java, src/main/java/com/example/hestiaapipostgres/models/Anunciante.java, src/main/java/com/example/hestiaapipostgres/models/Universitario.java, src/main/java/com/example/hestiaapipostgres/repository/AnuncianteRepository.java, src/main/java/com/example/hestiaapipostgres/repository/UniversitarioRepository.java, src/main/java/com/example/hestiaapipostgres/repository/UsuarioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/AnuncioService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java, src/main/java/com/example/hestiaapipostgres/services/UsuarioService.java
Adição da rota para descobrir a origem do usuário: anunciante ou universitário
Novo DTO, novo repository, nova rota, novo controller
Também houve a redução da URL das rotas
=> rota de origem do usuário

src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java, src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioController.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java
atualização da chave de busca das rotas de find de perfil de universitário e anunciante. agora a chave é o email
mudanças em UnviersitarioService, UniversitarioController, AnuncianteService, AnuncianteController
=> update profiles routes to email as a way of find

pom.xml, src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java, src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioController.java, src/main/java/com/example/hestiaapipostgres/controllers/UsuarioController.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterAdvertiserDTO.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterUniversityDTO.java, src/main/java/com/example/hestiaapipostgres/dto/update/UpdateAdvertiserDTO.java, src/main/java/com/example/hestiaapipostgres/models/Universitario.java, src/main/java/com/example/hestiaapipostgres/repository/UniversitarioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java, src/main/resources/application.properties
Consertando chamada da procedure de cadastro de universitário + fix rápido de mapeamento de update de anunciante
Alterações em DTOS e repositories
=> Consertando procedures

pom.xml, src/main/java/com/example/hestiaapipostgres/config/RedisConfig.java, src/main/java/com/example/hestiaapipostgres/config/SecurityConfig.java, src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java, src/main/java/com/example/hestiaapipostgres/controllers/JwtTokenController.java, src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioController.java, src/main/java/com/example/hestiaapipostgres/dto/InfoUserDTO.java, src/main/java/com/example/hestiaapipostgres/dto/TokenAccess.java, src/main/java/com/example/hestiaapipostgres/dto/perfil/AnuncianteProfileInfo.java, src/main/java/com/example/hestiaapipostgres/dto/perfil/UniversitarioProfileInfo.java, src/main/java/com/example/hestiaapipostgres/exceptions/GlobalExceptionHandler.java, src/main/java/com/example/hestiaapipostgres/models/Anunciante.java, src/main/java/com/example/hestiaapipostgres/models/Universitario.java, src/main/java/com/example/hestiaapipostgres/repositories/AnuncianteRepository.java, src/main/java/com/example/hestiaapipostgres/repositories/UniversitarioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/JwtTokenService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java, src/main/java/com/example/hestiaapipostgres/services/UsuarioService.java, src/main/resources/application.properties
Foi realizada a feature de implementar a configuração base do redis mais o seu uso em alguns endpoints, juntamente com a documentação do swagger de Anunciante e Universitário. Também foi implementada a configuração base do JWT para segurança em alguns endpoints, mas este fluxo ainda sofrerá alterações.
Foi também feita a fix rápida das procedures de cadastro.
Novos arquivos de configuração, alterações nos models e repositories, e um novo controller de JWT
=> feat: implementing redis + swagger

src/main/java/com/example/hestiaapipostgres/models/Anunciante.java, src/main/java/com/example/hestiaapipostgres/models/Universitario.java, src/main/java/com/example/hestiaapipostgres/repositories/AnuncianteRepository.java, src/main/java/com/example/hestiaapipostgres/repositories/UniversitarioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java
Foi realizada a implementação de uma nova coluna: tipo_conta que dirá se um usuário é ADMIN ou USER, para acesso a determinadas rotas com autenticação jwt
alterações no model e repositoy
=> feat: implementing field user type

src/main/java/com/example/hestiaapipostgres/controllers/AnuncianteController.java, src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/controllers/PagamentoController.java, src/main/java/com/example/hestiaapipostgres/dto/get/ImovelAnuncioDTO.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterPagamentoDTO.java, src/main/java/com/example/hestiaapipostgres/models/Anuncio.java, src/main/java/com/example/hestiaapipostgres/models/Imovel.java, src/main/java/com/example/hestiaapipostgres/models/Pagamento.java, src/main/java/com/example/hestiaapipostgres/models/Plano.java, src/main/java/com/example/hestiaapipostgres/repositories/AnuncioRepository.java, src/main/java/com/example/hestiaapipostgres/repositories/BoostRepository.java, src/main/java/com/example/hestiaapipostgres/repositories/PagamentoRepository.java, src/main/java/com/example/hestiaapipostgres/repositories/PlanoRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/AnuncioService.java, src/main/java/com/example/hestiaapipostgres/services/PagamentoService.java, src/main/java/com/example/hestiaapipostgres/services/UsuarioService.java
Endpoints de listagem de moradias barra anuncio por anunciante id e imovel id
novas services, queries personalizadas no repository de anuncio
=> endpoints de listagem de imoveis e anuncios

src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/repositories/AnuncioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncioService.java
Agora a busca de moradias por anunciante é por e-mail
só no tipo
=> fix route to email

src/main/java/com/example/hestiaapipostgres/dto/get/ImovelAnuncioDTO.java
=> mapping fields

src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/dto/get/ImovelAnuncioDTO.java, src/main/java/com/example/hestiaapipostgres/repositories/AnuncioRepository.java
=> agora é retornado o anuncio id ao inves do imovel id

src/main/java/com/example/hestiaapipostgres/controllers/PagamentoController.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterPagamentoDTO.java, src/main/java/com/example/hestiaapipostgres/models/Pagamento.java, src/main/java/com/example/hestiaapipostgres/models/Plano.java, src/main/java/com/example/hestiaapipostgres/repositories/PagamentoRepository.java, src/main/java/com/example/hestiaapipostgres/repositories/PlanoRepository.java, src/main/java/com/example/hestiaapipostgres/services/PagamentoService.java
endpoint de registro de pagamento completo e funcional
novo repository, service, e chamda a function
=> endpoint de registro de pagamento completo

src/main/java/com/example/hestiaapipostgres/models/Pagamento.java
=> fix field names

src/main/java/com/example/hestiaapipostgres/controllers/PagamentoController.java, src/main/java/com/example/hestiaapipostgres/models/Pagamento.java, src/main/java/com/example/hestiaapipostgres/repositories/PagamentoRepository.java, src/main/java/com/example/hestiaapipostgres/services/PagamentoService.java
adição de um endpoint de achar o pagamento pelo e-mail do usuário assinante
alteração no controller, service e repository
=> feat: endpoint find pagamento by user email

src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/repositories/AnuncioRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncioService.java
endpoint de achar uma moradia pelo id do anuncio
nova query no repository, novo método no service e endpoint no controller
=> endpoint de achar uma moradia pelo id do anuncio

src/main/java/com/example/hestiaapipostgres/config/SecurityConfig.java, src/main/java/com/example/hestiaapipostgres/controllers/JwtTokenController.java, src/main/java/com/example/hestiaapipostgres/controllers/PagamentoController.java, src/main/java/com/example/hestiaapipostgres/dto/TokenAccess.java, src/main/java/com/example/hestiaapipostgres/services/JwtTokenService.java
Implementação do token jwt para todas as requisições
no security config, qualquer reuiqisção agora precisa de autorização
=> feat: implementing jwt token authentication for all users

src/main/java/com/example/hestiaapipostgres/config/SecurityConfig.java, src/main/java/com/example/hestiaapipostgres/controllers/StatusController.java
endpoint GET que retorna uma mensagem de API viva somente para manter no keepalive
novo controller StatusController
=> keep alive route

src/main/java/com/example/hestiaapipostgres/config/SecurityConfig.java, src/main/java/com/example/hestiaapipostgres/controllers/StatusController.java
Adição de um endpoint sem autenticação para manter a aplicação no keep alive
novo controller
=> Get status

src/main/java/com/example/hestiaapipostgres/controllers/StatusController.java, src/main/resources/application.properties
Adicionando status no prod.
Adicionando status no prod.
=> Add status

src/main/java/com/example/hestiaapipostgres/config/SecurityConfig.java
dando permit all nos endpoints de registro de universitário e anunciante
=> fix security config

src/main/java/com/example/hestiaapipostgres/repositories/AnuncioRepository.java
Mudança no retorno do método de achar moradia pelo ID. agora retorna o id do anúncio, e não o do imóvel
mudança em um campo do repository de anúncio
=> fix: change return

src/main/java/com/example/hestiaapipostgres/config/SecurityConfig.java, src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioMoradiaController.java, src/main/java/com/example/hestiaapipostgres/dto/register/RegisterUniversityPropertyDTO.java, src/main/java/com/example/hestiaapipostgres/models/UniversitarioMoradia.java, src/main/java/com/example/hestiaapipostgres/repositories/UniversitarioMoradiaRepository.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioMoradiaService.java
POST  de entrada em uma moradia por um universitário
Nova service, repository e controller
=> university join property route

src/main/java/com/example/hestiaapipostgres/controllers/AnuncioController.java, src/main/java/com/example/hestiaapipostgres/controllers/UniversitarioMoradiaController.java, src/main/java/com/example/hestiaapipostgres/dto/get/ImovelAnuncioDTO.java, src/main/java/com/example/hestiaapipostgres/repositories/AnuncioRepository.java, src/main/java/com/example/hestiaapipostgres/repositories/UniversitarioMoradiaRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncioService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioMoradiaService.java
lista de universitários pelo id do imóvel
nova query nativa no repository, service e controller
=> lista de universitários pelo id do imóvel

src/main/java/com/example/hestiaapipostgres/repositories/PlanoRepository.java, src/main/java/com/example/hestiaapipostgres/services/AnuncianteService.java, src/main/java/com/example/hestiaapipostgres/services/AnuncioService.java, src/main/java/com/example/hestiaapipostgres/services/PagamentoService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioMoradiaService.java, src/main/java/com/example/hestiaapipostgres/services/UniversitarioService.java
=> merge dev main
